# Generated by Django 3.0.1 on 2019-12-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(default='new summary', max_length=200),
            preserve_default=False,
        ),
    ]
