# Generated by Django 3.0.1 on 2019-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='World', max_length=20),
            preserve_default=False,
        ),
    ]
